{
  description = "Add additional checks and more information from build logs and outputs to the reports generated by nixpkgs-review.";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: {
      packages.nixpkgs-review-checks = nixpkgs.legacyPackages.${system}.callPackage self {
        src = self;
      };
      defaultPackage = self.packages.${system}.nixpkgs-review-checks;
    });
}
