name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
